
export default {
    POST_PROJECT_DATA_ACTION: 'POST_PROJECT_DATA_ACTION',
    POST_WORKSPACE_DATA_ACTION: 'POST_WORKSPACE_DATA_ACTION',
    POST_LIST_DATA_ACTION: 'POST_LIST_DATA_ACTION',
    POST_TASK_DATA_ACTION: ' POST_TASK_DATA_ACTION'
}