export default {
    POST_PROJECT_DATA_MUTATION: 'POST_PROJECT_DATA_MUTATION',
    POST_WORKSPACE_DATA_MUTATION: ' POST_WORKSPACE_DATA_MUTATION',
    POST_LIST_DATA_MUTATION: 'POST_LIST_DATA_MUTATION',
    POST_TASK_DATA_MUTATION: 'POST_TASK_DATA_MUTATION'
}
  